###############
## 
####

GPU: [0,2,3]

VERBOSE: True

MODEL:
  MODE: 'Super_Resolution'
  SESSION: 'MMAFNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 10
  NUM_EPOCHS: 4000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 8e-5
  LR_MIN: 5e-7
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: True
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: '/home/jackyang/CC_object/HR/V13_Super_Resolution/datasets/trainData' # path to training data
  VAL_DIR: './datasets/validationData'    # path to validation data
  SAVE_DIR: './pretrained_model'     # path to save models and images
  # SAVE_IMAGES: False
  DISPLAY_ID: 1
  BACKWARD_TYPE: 'fused'
  TRAIN: True


